
# Placeholder for future Kubernetes-based runner deployment
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner
spec:
  replicas: 1
  template:
    spec:
      repository: org/repo
      image: my-custom-runner-image
      env: []
